# Generated by Django 6.0.7 on 2026-07-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Commonwealth Bank', max_length=150)),
                ('account_name', models.CharField(default='Glow State', max_length=150)),
                ('bsb', models.CharField(default='064 437', max_length=20)),
                ('account_number', models.CharField(default='10013757', max_length=40)),
                ('paypal_email', models.EmailField(default='Glowstatepeps@hotmail.com', max_length=254)),
                ('paypal_client_id', models.CharField(blank=True, default='', help_text='Public PayPal REST API client ID (sandbox or live) used to load the JS SDK on the storefront.', max_length=255)),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
