# Generated by Django 6.0.7 on 2026-08-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payid_name',
            field=models.CharField(default='T Amos', help_text='Name the customer will see matched to the PayID at their bank.', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payid_number',
            field=models.CharField(default='0491186505', help_text='Phone number (or email) registered as the PayID for real-time transfers.', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('payid', 'PayID')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('payid', 'PayID')], default='bank_transfer', max_length=30),
        ),
    ]
