# Generated by Django 6.0.7 on 2026-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paymentdetails_payid_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('payid', 'PayID'), ('paypal', 'PayPal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('payid', 'PayID'), ('paypal', 'PayPal')], default='bank_transfer', max_length=30),
        ),
    ]
