# Generated by Django 6.0.7 on 2026-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_payment_method_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('payid', 'PayID'), ('paypal_invoice', 'PayPal Invoice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('payid', 'PayID'), ('paypal_invoice', 'PayPal Invoice')], default='bank_transfer', max_length=30),
        ),
    ]
